### ISSUE TITLE
Make warnings errors

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#108]
We discussed this some time ago, but I figured it would be good to bring up again since we're starting to get lots of easy-to-fix warnings hiding actual issues. I'd like to make the compiler treat warnings as errors (except for signed/unsigned comparisons), which should hopefully reduce the number of warnings.

We can do this with `-Werror -Wno-error=sign-compare`.

How do other people feel about this?

**Comment by bvanessen** [comment]
Sounds good to me.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by davidHysom** [comment]
If this affects on LBANN, and not third party packages, I'm in favor.

Not sure why we should exclude signed/unsigned comparisons;

they're easy to fix with a cast, and that means someone has actually

looked, and hopefully thought, that the casting is OK and can't

possibly lead to a bug.

________________________________

**Comment by trb413** [comment]
For what it's worth, I agree with @davidHysom, re signed/unsigned compares. It's an annoying warning, but easy to fix. Third-party packages' warnings will be excluded assuming their headers were included via "-isystem" rather than "-I" (not sure how compiler-dependent that statement is), which CMake is pretty good about.

**Comment by ndryden** [comment]
Fair enough; consensus seems to be toward no more signed/unsigned errors.

Our third-party packages should already be included with `-isystem`, but I'll verify everything works. (And fix warnings/errors before I push this change.)

**Comment by ndryden** [comment]
An issue with this, and perhaps someone with better cmake skills than I can help: Adding `-Werror` to `CMAKE_CXX_FLAGS` (as done with our warnings) propagates it to Elemental, which then fails to build. Is there a good way to only set the flag for building LBANN but not dependencies?

**Comment by benson31** [comment]
One method might be to add it via `target_compile_options()` for the LBANN targets.

**Comment by bvanessen** [comment]
Can you give us an example of how to do that please.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by trb413** [comment]
`target_compile_options(lbann PUBLIC "-Werror")`. That can go anywhere in the CMakeLists.txt file after the `lbann` target has been added.

**Comment by trb413** [comment]
Also, just FYI, it's likely that that option is portable to the compilers that you care about most (it's as portable as `-Wall`), but it's not universal.

**Comment by ndryden** [comment]
I added that and it works for stuff in the model zoo, but not for warnings when building the lbann library itself-- any way to do that?

**Comment by trb413** [comment]
I didn't parse the CMakeLists.txt file all the way through. It looks like you'll want `target_compile_options(src PUBLIC "-Werror")` around where the `src` library is defined.

I would also have the `target_compile_options(lbann PUBLIC "-Werror")` line in there to guarantee that the option gets forwarded to the model zoo files. If that option gets propagated to `lbann` from `src`, there's no harm in repeating it. However, if that option gets lost, as I imagine it would since you just forward the `$<TARGET_OBJECTS:src>` generator expression to `lbann`, you will need to apply it again anyway to ensure it makes it to the model zoo files.

**Comment by trb413** [comment]
As a more general comment: if there are additional flags you would like to see passed to LBANN but not to external dependencies, you might consider something like

`
set(LBANN_CXX_FLAGS "${LBANN_CXX_FLAGS} -Werror -fmy-favorite-compiler-flags <etc>")
...
target_compile_options(src PUBLIC "${LBANN_CXX_FLAGS}")
...
target_compile_options(lbann PUBLIC "${LBANN_CXX_FLAGS}")
`
