### ISSUE TITLE
Number of Labels in ImageNet

### ISSUE THREAD

**Issue by samadejacobs** [LLNL/lbann#122]
Number of labels in ImageNet data reader is hardcoded to 1000, we need to generalize this to support arbitrary number of labels e.g., 21K+ for the entire ImageNet dataset

**Comment by ndryden** [comment]
The numpy and csv readers (if running with labels) support dynamically computing the number of labels in a dataset-- we can probably adapt this to ImageNet.

The basic idea is to do a pass over the label file in `load` and count the number of different classes seen (eg using an `unordered_set`).

**Comment by JaeseungYeom** [comment]
I added an interface to pass the width, the height, and the number of channels to allow image data size check with/without resizing. This interface also takes the number of labels. Since I was in there, I made a little more changes to accommodate the need. Basically, you can specify 'num_labels' in reader section of the prototext for data reader.
With little modification, you can also fit in a routine to dynamically determine the number of labels under a predefined condition.
