### ISSUE TITLE
New cmake environment does not seem to properly pickup changes to header files

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#15]
The new cmake build system will install the header files into the build directory and then use those for compiling the library.  However, when a change to a header file is made, it seems that the header files in the build directory are not updated and thus the stale header file is used rather than the new header file.

**Comment by ndryden** [comment]
I can confirm this occurs, but have not yet figured out a solution. I tried adding all the headers to the sources list and still didn't get anything.

It may be something related to dependencies, the generated `depend.make` files seem to refer to the `include` directory in the build directory, and not in the main LBANN directory, which may be breaking things.

I also have read some stuff about CMake being picky about relative versus absolute paths, so that may be a factor too.

**Comment by ndryden** [comment]
An additional note: This also effects source files that are not in the model zoo.
