### ISSUE TITLE
OpenCV JPEG parser is slow with Lustre

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#213]
I've found an interesting performance regression while profiling AlexNet (ImageNet-10, 256 mini-batch size; 1 node on Surface gpgpu). It takes ~35 sec/epoch when we get data from Lustre and ~25 sec/epoch when data is cached in `/tmp`. I expect the first epoch to be slower with Lustre data, but previous experiments showed similar timings for subsequent epochs since the files would reside in cache.

The culprit is [`cv::imread()`](https://github.com/opencv/opencv/blob/601e3aaf988b8450634b931c10900633622bad04/modules/imgcodecs/src/loadsave.cpp#L625), which takes 25.5% of the runtime with Lustre data and 1.5% with cached data. The worst increase shows up in [`cv::ExifReader::getExif()`](https://github.com/opencv/opencv/blob/601e3aaf988b8450634b931c10900633622bad04/modules/imgcodecs/src/exif.cpp#L119), which extracts an Exif tag from the JPEG file header and takes 15.3% of the runtime. This is necessary since the Exif header determines the picture orientation, but it is wonky that parsing the header takes more time than loading the entire image. The parse function repeatedly calls `std::istream::read` for two bytes at a time, so I have some hypotheses:
- LC systems are no longer caching as well as before. Every time we read two bytes, we have to get it remotely.
- This is caused by the Meltdown patch. Reading two bytes from a file stored in cache involves system calls that are slowed down by the patch.

We have some options:
- Data stores (#197) should bypass this issue since their behavior should be similar to caching data in `/tmp`. However, from what I understand, the initial implementation requires that we be able to store the entire data set on the compute nodes.
- Disabling Exif parsing brings back most of the performance, although not all. [`cv::findDecoder()`](https://github.com/opencv/opencv/blob/601e3aaf988b8450634b931c10900633622bad04/modules/imgcodecs/src/loadsave.cpp#L185), [`cv::JpegDecoder::readHeader()`](https://github.com/opencv/opencv/blob/601e3aaf988b8450634b931c10900633622bad04/modules/imgcodecs/src/grfmt_jpeg.cpp#L207), and [`cv::JpegDecoder::readData()`](https://github.com/opencv/opencv/blob/601e3aaf988b8450634b931c10900633622bad04/modules/imgcodecs/src/grfmt_jpeg.cpp#L389) together take up 10% of runtime. This is at best a temporary solution since it would involve throwing away the picture's orientation data.
- Contribute to OpenCV's JPEG parser. Loading header data in chunks instead of reading them two bytes at a time should be an easy fix. I am not sure how stringent their PR process is.

**Comment by ndryden** [comment]
Are you using libjpeg-turbo?

**Comment by timmoon10** [comment]
I'm using the defaults, so I don't think so?

**Comment by naoyam** [comment]
So, if cv::imread only takes 1.5% with caching, is that a problem?

**Comment by davidHysom** [comment]
*   Data stores (#197<https://github.com/LLNL/lbann/pull/197>) should bypass this issue since their behavior should be similar to caching data in /tmp. However, from what I understand, the initial pass requires that we be able to store the entire data set on the compute nodes.

FYI, data stores will eventually operate in two user selectable modes:

  - store entire data set on compute nodes

  - stage the compute nodes' portion of the data somewhere (/tmp, ssd, etc), and read as needed.

Initially I'm implementing the first option for several data readers (imagenet, mulit_image, pilot2)) since this should give the best performance for datasets that can fit in memory. I'll work on the second option in the future.


 "I expect the first epoch to be slower with Lustre data, but previous experiments showed similar timings for subsequent epochs since the files would reside in cache."


How sure are you that *all* of the data resides in cache?


IMHO, I wouldn't worry about repeatable or degraded timings when reading from lustre. I simply expect timing to be horrible, esp. when reading lots of small files, and esp. esp. since you've no idea who else is banging away on lustre.


________________________________

**Comment by JaeseungYeom** [comment]
instead of cv::imread(), you can also use cv::imdecode() on a block of memory as in lbann::image_utils::import_image()
