### ISSUE TITLE
Hints for layer output dimensions

### ISSUE THREAD

**Issue by samadejacobs** [LLNL/lbann#320]
Something akin to [tf.like_zero(tensor)](https://www.tensorflow.org/api_docs/python/tf/ones_like) and [tf.like_one(tensor)](https://www.tensorflow.org/api_docs/python/tf/zeros_like), a good use case will be (Cycle)GAN. This will generalize previous modification to MNIST reader in #296 and also important for data_reader refactoring. One major concern here is that we may have to decouple target layer from input layer (again?)

**Comment by timmoon10** [comment]
How about we generalize? We add functionality so that layers can take the dimensions of another layer. To emulate tf.like_zero, you would construct a constant_layer (with value 0) and set it to have the dimensions of the other layer. I'm thinking about this approach because it could also replace our current functionality where you can set the fully-connected layer output to match the data readers. It could also be useful in recurrent networks.

**Comment by samadejacobs** [comment]
Yes you are right, constant_layer will serve that purpose for both like_zero and like_=one . I have actually been using constant_layer as described except that I manually specify "num_neurons".

**Comment by timmoon10** [comment]
Closed with #703.
