### ISSUE TITLE
GPU-enabled data augmentation pipeline

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#338]
Update the data augmentation pipeline to take advantage of the new GPU matrices.

**Comment by timmoon10** [comment]
In principle, we support some data augmentation with the crop and bilinear resize layers. We don't support JPEG decoding on GPUs and the layer-based approach requires fixed image dimensions.

**Comment by timmoon10** [comment]
I think the current CPU-based data preprocessing pipeline is sufficient for several reasons:
- Preprocessing is currently performed on background CPU threads, which overlap efficiently with GPU-based compute and communication.
- In practice, data ingestion is mostly bottlenecked by IO. Overall training is typically bottlenecked by gradient allreduces.
- Preprocessing should be done independently on each data sample since they may have different dimensions. This increases the overhead from launching GPU kernels and reduces the amount of bulk computation we can expose to the GPU.

Of course, this may be worthwhile revisiting depending on future applications:
- If preprocessing is extremely compute-intensive and amenable to a GPU implementation.
- If preprocessing takes a small input and produces a large output, so CPU-GPU data transfers are reduced by performing the preprocessing on GPU. Image decoding is a possible case.

**Comment by davidHysom** [comment]
>In practice, data ingestion is mostly bottlenecked by IO
Can you comment: if using the data store this should only be an issue during the first epoch. If that's not the case ... well, lots of questions here. Probably best to discuss on slack.

**Comment by timmoon10** [comment]
Hm, I didn't think about the data store. In any case, I don't think there's much evidence right now that preprocessing is a major bottleneck.
