### ISSUE TITLE
building LBANN using OpenMPI

### ISSUE THREAD

**Issue by JaeseungYeom** [LLNL/lbann#465]
I remember that we were able to do this long time ago, but now I am unable to do so.
I am trying it on Pascal using the build script, the latest OpenMPI/3.0.1 and gcc/4.9.3.
(I also tried gcc/6.1.0 by commenting out the line loading gcc/4.9.3 for pascal in the build script, and still got the same failure)
I commented out the line to pick up the sideinstall mpi in the build script and used the option '--mpi openmpi' only.
It fails at the LAPACK linktest. (BTW, clang compilation started to fail as well since yesterday or today.)
When using OpenMPI/2.1.0, I encountered a different error as below:
```
/opt/cudatoolkit/9.1/bin/nvcc   -I/p/lscratchh/.../lbann/build/gnu.Release.pascal.llnl.gov/hydrogen/src/external/suite_sparse/include -I/p/lscratchh/.../lbann/build/gnu.Release.pascal.llnl.gov/hydrogen/src/include -I/p/lscratchh/.../lbann/build/gnu.Release.pascal.llnl.gov/hydrogen/src/include/El -I/p/lscratchh..../lbann/build/gnu.Release.pascal.llnl.gov/hydrogen/build/include -isystem=/usr/tce/packages/openmpi/openmpi-2.1.0-gcc-4.9.3/include -isystem=/opt/cudatoolkit/9.1/include -isystem=/p/lscratchh/.../lbann/build/gnu.Release.pascal.llnl.gov/install/include  -O3 -DNDEBUG -Xcompiler=-fPIC   -fexceptions -arch=sm_30 -std=c++11 -x cu -c /p/lscratchh/.../lbann/build/gnu.Release.pascal.llnl.gov/hydrogen/src/src/blas_like/level1/GPU/Axpy.cu -o CMakeFiles/Hydrogen.dir/src/blas_like/level1/GPU/Axpy.cu.o
nvcc fatal   : Unknown option 'fexceptions'
```

I also tried spack script with the option '-m openmpi', and got the error saying
"The spec 'openmpi' is configured as not buildable, and no matching external installs were found"

Am I missing something?

**Comment by JaeseungYeom** [comment]
Another question is if we can expose the OPENBLAS_TAG cmake variable to user.

**Comment by benson31** [comment]
I have built LBANN on pascal using OpenMPI 3.1.0 (in the brain workspace, under utils/toss3). It was rough -- nvcc couldn't find some gcc headers at one point and then opencv has a bunch of bad code for dealing with intel intrinsics that I had to manually fix. And after all that fun, the punch line was that LBANN hangs in the setup phase. I'm trying to investigate why but it's kind of a pain since it hangs in `El::Initialize()` if I'm running in TV.

I assume you mean expose `OPENBLAS_TAG` through `build_lbann_lc.sh`? If so, we _could_ do that, but it would be odd to do that and not expose all the other `<PACKAGE>_TAG` variables. Otherwise, you can just pass `-DOPENBLAS_TAG=whatever` to the superbuild's CMake. You could also locally modify your version of `build_lbann_lc.sh` to have this cache variable set.

**Comment by JaeseungYeom** [comment]
The reason I hope it to be exposed to build_lbann_lc.sh is that OpenBLAS and Lapack are typically the source of compilation or linking error and the usual road block in using various compilers. But you are right that I can try superbuild or local modification.

**Comment by benson31** [comment]
I’ve also thought about adding `--additional-cmake-arguments=<some string of arguments>`. This might be the best way so that helpful-but-not-common CMake arguments can be easily passed through the build script without manually exposing them.

**Comment by bvanessen** [comment]
I have some concerns about blowing up the build_lbann_lc.sh script with lots of options for different compilers and libraries.  I would like to maintain that script as a straightforward way to get started in building lbann, but I really thing that getting comfortable with a spack build environment is a more maintainable way to tacked different library / compiler options.

Brian C. Van Essen
vanessen1@llnl.gov<mailto:vanessen1@llnl.gov>
(w) 925-422-9300
(c) 925-290-5470

On Jun 26, 2018, at 5:10 PM, Tom Benson <notifications@github.com<mailto:notifications@github.com>> wrote:


I’ve also thought about adding --additional-cmake-arguments=<some string of arguments>. This might be the best way so that helpful-but-not-common CMake arguments can be easily passed through the build script without manually exposing them.

**Comment by benson31** [comment]
My counterargument to that sentiment is that spack seems wildly unstable, and some of our dependencies (e.g., openblas) are *very* closely tied to compilers as they rely on special instructions or this intrinsic or that. Every time we have to touch spack, there's a lot of overhead. Of course my personal solution to this hassle is to just use the superbuild so I can make it do whatever I want, but IMNSHO, it would be a good thing to add a way to pass generic CMake arguments into the build script as a speedy alternative to having to stop work and then spend time debugging, hacking apart, and patching spack recipes every time a corner case is discovered, not to mention the time one then has to invest arguing with spack folks to merge your (oddly) controversial PR to make any change permanent. In this worldview, the speedy fix that Awesome Developer hacked in through `--additional-cmake-arguments` or whatever would then be integrated into the build script and/or spack recipe(s) when it's shown to solve whatever corner-case problem that is encountered, assuming Awesome Developer is a nice person. This should cut down the number of times we have to break open the build script when we're outside the <really old gcc>+mvapich2 world that's extensively tested.
