### ISSUE TITLE
Support bilinear upsampling

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#478]
Support a bilinear upsampling layer.

Similar to #477, except this does not have multiple filters or learnable parameters.

**Comment by timmoon10** [comment]
More generally, it would be nifty to have image resizing with bilinear interpolation.

**Comment by timmoon10** [comment]
While this issue is closed, I should note that bicubic interpolation is preferred by the graphic design community (it's Photoshop's default) and sinc interpolation is theoretically optimal in a digital signal processing sense (although people seem to prefer Lanczos interpolation). In any case, resizing algorithms seem like a very deep rabbit hole.
