### ISSUE TITLE
Broken link: http://software.llnl.gov/lbann/

### ISSUE THREAD

**Issue by naoyam** [LLNL/lbann#516]
The LBANN URL linked from the top page of this repository seems to be broken.

**Comment by davidHysom** [comment]
I'm not sure what this used to point to; documentation?  https://software.llnl.gov is still there, and lbann is listed; the link points to our github repo (It looks like all links on software.llnl.gov now point to github).   like The person to contact is Ian Lee.

**Comment by DylanMcKinney** [comment]
It did used to point to documentation. When we moved from gh pages to read the docs that link went dead since it redirects to the now gone gh pages. We need it to point to our read the docs build but I don't know how to change that link to do so

**Comment by bvanessen** [comment]
I will work on it.

Brian C. Van Essen
vanessen1@llnl.gov<mailto:vanessen1@llnl.gov>
(w) 925-422-9300
(c) 925-290-5470

On Jul 13, 2018, at 8:46 AM, DylanMcKinney <notifications@github.com<mailto:notifications@github.com>> wrote:


It did used to point to documentation. When we moved from gh pages to read the docs that link went dead since it redirects to the now gone gh pages. We need it to point to our read the docs build but I don't know how to change that link to do so

**Comment by ShadenSmith** [comment]
FYI, the link is still broken.

**Comment by bvanessen** [comment]
This is fixed.
