### ISSUE TITLE
Build failure on Catalyst and Quartz

### ISSUE THREAD

**Issue by timmoon10** [LLNL/lbann#529]
### Details
When building on Catalyst or Quartz, the super build will fail in Hydrogen with an error like the following:
```text
In file included from /g/g14/zaman1/lbann/build/gnu.Release.catalyst.llnl.gov/hydrogen/src/include/El/blas_like/level1/impl.hpp:22,
                 from /g/g14/zaman1/lbann/build/gnu.Release.catalyst.llnl.gov/hydrogen/src/include/El/blas_like/level1.hpp:13,
                 from /g/g14/zaman1/lbann/build/gnu.Release.catalyst.llnl.gov/hydrogen/src/src/blas_like/level1/HilbertSchmidt.cpp:10:
/g/g14/zaman1/lbann/build/gnu.Release.catalyst.llnl.gov/hydrogen/src/include/El/blas_like/level1/Copy.hpp:384:27: error: ambiguous template specialization 'Copy<>' for 'void El::Copy(const El::Matrix<long long int>&, El::Matrix<long long int>&)'
   EL_EXTERN template void Copy \
                           ^~~~
/g/g14/zaman1/lbann/build/gnu.Release.catalyst.llnl.gov/hydrogen/src/include/El/macros/Instantiate.h:10:23: note: in expansion of macro 'PROTO'
 # define PROTO_INT(T) PROTO(T)
                       ^~~~~
/g/g14/zaman1/lbann/build/gnu.Release.catalyst.llnl.gov/hydrogen/src/include/El/macros/Instantiate.h:88:1: note: in expansion of macro 'PROTO_INT'
 PROTO_INT(Int)
 ^~~~~~~~~
 ```

I believe this is from a bug in GCC 8 (correct me if I'm wrong @benson31). We should change the defaults in the build script so things work out of the box.

### Command to reproduce error
```sh
scripts/build_lbann_lc.sh --verbose --clean-build
```

**Comment by benson31** [comment]
It's a GCC 8 bug.

**Comment by davidHysom** [comment]
I ran into a different bug in GCC 8 last week.

Am thinking: not ready for prime-time.

________________________________

**Comment by benson31** [comment]
Dave, what's your bug? I have a reproducer for the bug that Tim is describing, so if you have one or I could create one for yours, I'll add it to my bug report.

Basically, something in the intersection function overload resolution and template deduction is failing for the case where SNIFAE is used as `...,typename=EnableIf<boolean>>`. The reason I believe this to be a compiler bug is that it succeeds and the correct overload is selected if one changes the code to be `...,EnableIf<boolean,int> = 0>`. Moreover, it also succeeds if one implicitly instantiates the template rather than explicitly instantiating the template. This is either a compiler bug or a small dusty corner of the standard that GCC8 got right and literally every other compiler I can find gets wrong (XL, clang 4, clang 5, clang 6, clang dev, up-to-date appleclang, gcc 4.7.3, gcc 4.7.4, gcc 4.8, gcc 4.9, even gcc 5.*, gcc 6.*, gcc 7.*, pgi's compiler, intel).
