### ISSUE TITLE
Handling partial mini-batches in layers with data-parallel distribution

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#58]
We need to check to see how we are handling the last mini-batch in an epoch that doesn't have the full number of samples.  Specifically, when we distribute the data I don't know that we properly balance the partial data set or zero out the unused sample slots.

**Comment by timmoon10** [comment]
- We handle partial mini-batches by using matrix views that exclude unused matrix columns.
- Since Elemental assigns columns of STAR,VC matrices in round-robin fashion, the process with the heaviest load has at most one more column than the process with the lightest load.
- The mini-batch size on the GPU is fixed at the setup time since reducing the mini-batch size sometimes increases the required workspace. The runtime is thus unaffected by a partial mini-batch. For forward prop, it makes no difference if unneeded columns are filled with junk since we don't copy it back to the CPU. For backward prop, the unneeded columns can affect the weight gradients. To avoid this, the initial error signal for unneeded columns is set to zero. Mathematically, the error signal should remain zero throughout the entire backprop, although it may be safer to manually zero out the unneeded columns.

**Comment by bvanessen** [comment]
Good explanation, my concern was with the unused parts of the GPU matrices. It may be worth checking to make sure that they are properly canceled out.



Brian Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) ‭925-290-5470‬
________________________________

**Comment by timmoon10** [comment]
Unused matrix columns on the GPU are zeroed out during back prop as of 49706e902d4ab4ab966bb787baaf803ba19023ed.
