### ISSUE TITLE
GPU memory allocation in multiple model files scenario

### ISSUE THREAD

**Issue by samadejacobs** [LLNL/lbann#604]
Current draft implementation of cycle GAN is a concatenation of three multiple model (model1, model2, and model3) files (a separate work in progress to have all the "magic" done in one single model file). In the meantime, GPU memory allocation/setup failed in model3 (Failed to allocate GPU memory with message: "out of memory" (536870912 bytes requested, 459145216 bytes available, 17071734784 bytes total), but without exiting causing model1 and model2 wasted computation. Model3 eventually failed because it could memory allocation already failed and weights can not be copied from model1 and model2 to model3. I think a fix would be for the code to exit immediately memory allocation/setup fail. A separate question is: where have all the memory gone?

**Comment by ndryden** [comment]
The reason it doesn't exit is because `lbann_cygan.cpp` catches the exception within `build_model_from_prototext` and returns normally to resume execution, whereas `lbann.cpp` exits cleanly.

As for where the memory is going, you might try running with the `gpu_memory_usage` callback we have, assuming you can finish initialization.

**Comment by timmoon10** [comment]
I have noticed DenseNet taking a lot of memory, although I'm not sure whether that is related to the architecture changes we've been making. I think a GPU memory regression test would be helpful if we're allocating something unnecessarily (see #351).
