### ISSUE TITLE
Autoencoder crashes when MB size is less than LBANN Tasks/MPI Processes

### ISSUE THREAD

**Issue by samadejacobs** [LLNL/lbann#62]
May be a general problem in LBANN/Elemental but was observed with NCI experiment from one of LBANN users. 

A quick debug indicate error coming from Elemental View : 
void El::View(El::ElementalMatrix<T>&, El::ElementalMatrix<T>&, El::Int, El::Int, El::Int, El::Int) [with T = float; El::Int = long long int]
Process 18 caught error message:
Matrices must have the same distribution

**Comment by bvanessen** [comment]
I can certainly see that happening in certain cases.  It may be that someone doesn’t have data, but they are trying to mix it with a local matrix or something.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by timmoon10** [comment]
I don't run into problems when I run lbann_cnn_mnist or lbann_alexnet with 4 nodes and mini-batch size 3. I'll rerun with a debug build.

**Comment by timmoon10** [comment]
Nikoli and I both reproduce this bug when running with a debug build of Element. The happens for both fully-connected and convolutional networks.

**Comment by ndryden** [comment]
I have fixed the issue with `El::View`: The `m_prev_error_signal` for target layers is not used, but a view was being set anyway. `Layer` now checks this before creating the view.

However, since `m_prev_error_signal` is not used in the target layer, I don't think this actually had an impact on anything. I'm no longer getting any Elemental errors when running `dnn_mnist` with the debug version of Elemental.

**Comment by bvanessen** [comment]
Is this issue fixed for the NCI experiments?

**Comment by samadejacobs** [comment]
@bvanessen , No but am on it. The "El::View fix" may not be related to the original problem.

**Comment by timmoon10** [comment]
LBANN runs fine when I run LeNet with a mini-batch size of 7 on 8 Pascal nodes (2 procs/node). Looks like this problem's gone away.
