### ISSUE TITLE
Format the code to an unified coding style

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#65]
We have a new script to apply astyle to the entire code base:

lbann/scripts/formatCode.py After reviewing the astyle docs, the options: -s2 --style=google,
which I think gives the indents that we want.

**Comment by bvanessen** [comment]
Please add the following flags as well:

--pad-oper / -p
--add-braces / -j
--convert-tabs / -c
--align-pointer=name   / -k3
--align-reference=type   / -W1

**Comment by davidHysom** [comment]
suggest this be divided into separate issues. From easiest to hardest:
1. format code using astyle. Run this periodically, automagically
2. name changes to protected and private variables per the m_XX convention. Note this is easy, because it does not affect anything outside of a give class
3. change class names to comply with our coding convention, e.g, Layer -> layer I believe this is mostly completed
4. change public method names to conform to camelCase -- oops, I meant our coding convention. This is most difficult, since it may touch a lot of our codebase.

**Comment by bvanessen** [comment]
Done via v0.93 release. f5878cfa0bf3a32fdcf9a66083ed88f16fb5876e
