### ISSUE TITLE
Compile with all warnings and leave the flags on

### ISSUE THREAD

**Issue by bvanessen** [LLNL/lbann#71]

**Comment by ndryden** [comment]
I've enabled the following warnings: `-Wall -Wextra -Wnon-virtual-dtor -Wshadow`.
I've explicitly disabled unused parameter warnings, since those tend to be spurious. We might also consider `-Weffc++`, but that has a lot of spurious warnings too.

Currently the code has a *lot* of unused variable and shadowing warnings. I'll close this issue once all the warnings are cleaned up.

**Comment by ndryden** [comment]
There are a few remaining warnings, but this is basically complete, so I'm closing it.
