### ISSUE TITLE
Layer variable names

### ISSUE THREAD

**Issue by ndryden** [LLNL/lbann#8]
We should fix the variable naming scheme in the `Layer` class and its children. `WB` and `Ds` and whatnot are somewhere between mostly and completely unintelligible.

**Comment by timmoon10** [comment]
I propose the following name replacements for the following matrices in lbann_layer.hpp:
-----------------------------------------
| Matrix | Description | Proposed Name |
-----------------------------------------
| WB | Weight-bias matrix | m_weights |
| WB_D | Gradient w.r.t. weight-bias matrix | m_weights_gradient |
| Zs | Output of forward pass linear transform | m_preactivations |
| Acts | Layer activations | m_activations |
| Ds | Error signal from "previous" layer | m_prev_error_signal |
| Ds_temp | Error signal to "next" layer | m_error_signal |
-----------------------------------------

**Comment by timmoon10** [comment]
Honestly, I think we should split up fully-connected layers, activation layers, and dropout layers so that we don't have to deal with the awkward Zs/m_preactivations matrix. In my proposed scheme, every layer will have four matrices: m_prev_activations, m_activations, m_prev_error_signal, and m_error_signal. m_prev_activations and m_prev_error_signal will point to the data in the "previous" layer if the data distribution is the same and will make a copy otherwise (thus, they will usually take up little memory and will save us the cost of doing multiple data redistributions). The current organization of lbann_layer.hpp requires that we pass an optimizer as an input, which limits us to optimize just one matrix. I suggest that we pass an optimizer factory to the layer and instantiate the optimizer internally. This will be useful if we want multiple optimizers (e.g. for filters and biases in convolutional layers). Finally, I don't like having an extra row of ones on the activations (so every activation matrix has NumNeurons+1 rows), but I haven't thought of a clean way to deal with this.
