### ISSUE TITLE
CUB version is outdated

### ISSUE THREAD

**Issue by naoyam** [LLNL/lbann#882]
The version we use is 1.5.2, whereas the latest is 1.8.0. There seem several bug fixes around the caching allocator, we should upgrade the version.

**Comment by naoyam** [comment]
I don't see any problem building with v1.8.0 of CUB. Have not yet run it, though. Since this can potentially impact pretty much every model, can you also try the latest version --> @ndryden @timmoon10 ? The change should be just one line in `superbuild/cub/CMakeLists.txt`, where `1.5.2` should be replaced with `1.8.0`.

**Comment by ndryden** [comment]
Will test on Lassen with my usual ResNet stuff once it's back.

**Comment by ndryden** [comment]
Tested and it works fine.

**Comment by timmoon10** [comment]
Perhaps we should just link to the CUB that comes with the CUDA SDK.

**Comment by naoyam** [comment]
Created a PR #884

**Comment by benson31** [comment]
On that note, what I want to do is prefer an external CUB but fall back on the SDK. That way, we can get bug fixes, new features, etc, faster than the SDK updates (assuming the APIs are the same). But I also want to make CUB required (because, frankly, I don't know what would happen without it). The first choice will be an external CUB, the fallback will be the one that ships with the SDK. Does that sound reasonable? (I'll do the work to make this happen, but it will be next week at the earliest; I assume this is not actively affecting anyone right now...)

**Comment by naoyam** [comment]
@timmoon10 It seems it's supposed to be hidden from users as it is located in `include/thrust/system/cuda/detail/cub`.

**Comment by benson31** [comment]
Oh. That suggests to me that they could in theory drop support in the SDK at some point... :/

**Comment by naoyam** [comment]
@benson31 The next thing I'm going to do is to apply a patch to CUB, so the SDK option doesn't seem to work.

**Comment by naoyam** [comment]
Closed by #884. Please let us know if anyone noticed unusual memory consumption.
